In [1]:
from qutip import basis, identity, ket2dm
import numpy as np
from contextuality.measurement_scenario import MeasurementScenarioImplementations
from contextuality.empirical_model import EmpiricalModel

In [2]:
KCBS = MeasurementScenarioImplementations.KCBS()

angle = np.pi / 5
Z_angle = np.sqrt(np.cos(angle))

zero, one, two = [basis(3, i) for i in range(3)]

# In Simple Hardy-Like Proof... By Cabello

ket1 = zero + Z_angle * two
ket1 = ket1.unit()

ket2 = np.cos(4*angle) * zero + np.sin(4*angle) * one + Z_angle * two
ket2 = ket2.unit()

ket3 = np.cos(2*angle) * zero - np.sin(2*angle) * one + Z_angle * two
ket3 = ket3.unit()

ket4 = np.cos(2*angle) * zero + np.sin(2*angle) * one + Z_angle * two
ket4 = ket4.unit()

ket5 = np.cos(4*angle) * zero - np.sin(4*angle) * one + Z_angle * two
ket5 = ket5.unit()


Ps = [eval(f"ket2dm(ket{i})") for i in range(1,6)]
As = [identity(3) - 2*P for P in Ps]
PVMs = [ [ket2dm(a.eigenstates()[1][0]).full(), (ket2dm(a.eigenstates()[1][1]) + ket2dm(a.eigenstates()[1][2])).full()] for a in As]

In [3]:
em = EmpiricalModel(KCBS)
rho = ket2dm(two).unit().full()
em.quantum_realisation(rho, PVMs)

In [4]:
print(np.round(em.mvector,3))
NCF = em.compute_cf()['NCF']
print(f"The NCF is {NCF:.3f}")

[[-0.     0.447  0.447  0.106]
 [ 0.     0.447  0.447  0.106]
 [ 0.     0.447  0.447  0.106]
 [ 0.     0.447  0.447  0.106]
 [-0.     0.447  0.447  0.106]]
The NCF is 0.528


In [5]:
# Quantum violation value:
CF = em.compute_cf()['CF']
CF * -5 + (1-CF) * -3

np.float64(-3.9442719099991574)